title: Markus Wehr # your name (or website title) here
logo: "/images/headshot.png?raw=true" #"/images/headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my website!<br><br>
  Education:<br>
  MSc Analytics; MSc Mgmt, Finance and Accounting<br><br>
  Experience:<br>
  Data Science, Banking, and Consulting<br><br>
  Technical skills:<br>
  Python, R, Spark, SQL, Hadoop, Hive, MongoDB, GCP, Git, Tableau, MS Office<br><br>
  Languages:<br>
  Fluent in German and English<br><br>
  <br>
  <a href="https://www.linkedin.com/in/markus-wehr">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-158113697-1 # your Google Analytics tracking ID here
